symbol: NIFTY
max_exposure_per_trade: 3000
daily_loss_limit: 6000
max_trades_per_day: 6
rr_target: 3
day_shift:
  start_ist: "09:15"
  end_ist:   "15:29"
night_shift:
  start_ist: "18:00"
  end_ist:   "08:00"
oc_refresh_secs_day: 10
oc_refresh_secs_night: 60
sheet:
  trades_tab: "Trades"
  signals_tab: "Signals"
  levels_tab: "OC_Live"
  perf_tab: "Performance"
  events_tab: "Events"
